import { existsSync } from "node:fs";
import { join } from "node:path";
import { checkConfig } from "./config.mjs";
import { checkLayout } from "./layout.mjs";
import { checkConstitution } from "./constitution.mjs";
import { checkEgress } from "./egress.mjs";
import { checkCriteria, checkCriteriaIndex } from "./criteria.mjs";
import { checkSeparation } from "./separation.mjs";
import { checkGenerated } from "./generated.mjs";
import { checkTests } from "./tests.mjs";

// `opts.skip` names check ids to leave out of the result entirely — not run and not
// reported, as distinct from a check that ran and passed. `buildPersonaPrompt` is the
// caller that needs this: it runs `runChecks` against whatever branch a proposal is
// being ruled on, and `checkCriteriaIndex` compares the live parse of every
// `spec/domains/*.md` file on that branch against `spec/criteria-index.json` — which is
// only ever regenerated by `ratify`. An archaeology proposal branch, by design, adds
// fresh `D-` criteria that no `ratify` run has touched yet, so once any domain in the
// project has been ratified once (and `criteria-index.json` therefore exists at all —
// see that check's own "a project with no index yet passes" comment), every later
// archaeology proposal's checks show the index as stale for criteria that were never
// supposed to be in it in the first place. That is not a fault in the proposal being
// ruled on, so the persona is shown the rest of the checks with this one left out.
export async function runChecks(projectDir, opts = {}) {
  if (opts.self) return [checkEgress(projectDir, { self: true })];
  const skip = new Set(opts.skip ?? []);
  const cfg = checkConfig(projectDir);
  const ctx = { config: cfg.config };
  const checks = [cfg, checkLayout(projectDir, ctx), checkConstitution(projectDir, ctx), checkEgress(projectDir, ctx)];
  // `spec/domains` is only meaningful once a project has run archaeology (or has hand-
  // authored criteria in it); a project that has not reached that stage yet has nothing
  // for this check to read and is not penalised for it.
  if (existsSync(join(projectDir, "spec", "domains"))) {
    checks.push(checkCriteria(projectDir, ctx));
    checks.push(checkCriteriaIndex(projectDir));
  }
  // The acceptance harness (fixtures, adapters, the two exemption yaml files) is laid
  // down before any test is written, so `tests/` existing is what separation and
  // generated-drift are meaningful against. `checkTests` needs the ratified index too —
  // a project with `tests/` but no `spec/criteria-index.json` yet has no accepted
  // criteria for a spec file's header to be checked against.
  if (existsSync(join(projectDir, "tests"))) {
    checks.push(checkSeparation(projectDir));
    checks.push(checkGenerated(projectDir));
    if (existsSync(join(projectDir, "spec", "criteria-index.json"))) checks.push(checkTests(projectDir, ctx));
  }
  return checks.filter((c) => !skip.has(c.id));
}
