// Reads the contract (`spec/contract/surface.yaml`, `personas.yaml`, `observables.yaml`)
// and the seed manifest (`tests/seed/manifest.yaml`) and turns them into the TypeScript a
// blind test-writing agent imports instead of a locator or a URL: `Surface`/`<Page>`
// interfaces, the persona table, and the seed handles. The generator is deterministic —
// same contract in, same bytes out — so a later check can compare `tests/generated/*`
// against `generateTypes(loadContract(dir))` and flag drift instead of trusting that
// nobody hand-edited a generated file.
import { join } from "node:path";
import { parse } from "yaml";
import { readText, writeText } from "../lib/fsx.mjs";

// Paths are relative to the project directory and doubled as the `file` field on any
// error the loader reports, so they stay path-shaped strings (forward slashes) rather
// than being built with `path.join`, which would flip to `\` on Windows.
const SURFACE_FILE = "spec/contract/surface.yaml";
const PERSONAS_FILE = "spec/contract/personas.yaml";
const OBSERVABLES_FILE = "spec/contract/observables.yaml";
const MANIFEST_FILE = "tests/seed/manifest.yaml";

const HEADER = "// generated by sdlc from spec/contract and tests/seed/manifest.yaml; do not edit";

// A missing contract file is not an error — a fresh project has none of them yet, and
// `contract` fills them in over several stages — so `undefined` here means "wasn't
// there" and every caller below treats that the same as an empty document. A file that
// exists but fails to parse as YAML is different: that is worth surfacing, so it is
// pushed onto `errors` and then also treated as empty, so one malformed file doesn't stop
// the other three from loading.
function readYaml(dir, relPath, errors) {
  let text;
  try {
    text = readText(join(dir, relPath));
  } catch (e) {
    if (e.code === "ENOENT") return undefined;
    throw e;
  }
  try {
    const parsed = parse(text);
    return parsed === null || parsed === undefined ? {} : parsed;
  } catch (e) {
    errors.push({ file: relPath, message: `${relPath} is not valid YAML: ${e.message}` });
    return undefined;
  }
}

// Structural checks for `pages: [...]`: an id, a route, every action/observation value an
// object. Invalid entries are still returned (nothing here drops or repairs a page) —
// `writeGenerated` refuses to generate from a contract that has errors, so the caller
// that needs a clean list already gets one for free; a caller reading `loadContract`
// directly gets the raw shape plus a full account of what is wrong with it.
function validateSurface(parsed, errors) {
  const pages = Array.isArray(parsed?.pages) ? parsed.pages : [];
  const seenIds = new Set();
  for (const [i, page] of pages.entries()) {
    const hasId = page && typeof page === "object" && typeof page.id === "string" && page.id.length > 0;
    const label = hasId ? `page "${page.id}"` : `page[${i}]`;
    if (!hasId) {
      errors.push({ file: SURFACE_FILE, message: `${label} is missing "id"` });
    } else if (seenIds.has(page.id)) {
      errors.push({ file: SURFACE_FILE, message: `duplicate page id "${page.id}"` });
    } else {
      seenIds.add(page.id);
    }
    const hasRoute = page && typeof page === "object" && typeof page.route === "string" && page.route.length > 0;
    if (!hasRoute) errors.push({ file: SURFACE_FILE, message: `${label} is missing "route"` });
    for (const group of ["actions", "observations"]) {
      const map = page && typeof page === "object" ? page[group] : undefined;
      if (!map || typeof map !== "object") continue;
      for (const [key, value] of Object.entries(map)) {
        if (!value || typeof value !== "object" || Array.isArray(value)) {
          const noun = group === "actions" ? "action" : "observation";
          errors.push({ file: SURFACE_FILE, message: `${label} ${noun} "${key}" is not an object` });
        }
      }
    }
  }
  return { pages };
}

function validatePersonas(parsed, errors) {
  const personas = Array.isArray(parsed?.personas) ? parsed.personas : [];
  personas.forEach((p, i) => {
    const hasId = p && typeof p === "object" && typeof p.id === "string" && p.id.length > 0;
    if (!hasId) errors.push({ file: PERSONAS_FILE, message: `persona[${i}] is missing "id"` });
  });
  return { personas };
}

// The manifest is `{ description, <group>: { <handle>: <value> }, ... }`. Every group
// other than `description` is a map of handle name to the identifier a test refers to it
// by, which is either the identifier itself (a bare string) or an object that names it
// under `id` alongside whatever else the seed needs (an email, say).
function validateManifest(parsed, errors) {
  const manifest = parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : {};
  for (const [groupKey, group] of Object.entries(manifest)) {
    if (groupKey === "description") continue;
    if (!group || typeof group !== "object" || Array.isArray(group)) continue;
    for (const [handle, value] of Object.entries(group)) {
      const isString = typeof value === "string";
      const isObjectWithId = value && typeof value === "object" && !Array.isArray(value) && "id" in value;
      if (!isString && !isObjectWithId) {
        errors.push({
          file: MANIFEST_FILE,
          message: `manifest handle "${groupKey}.${handle}" is not a string or an object with "id"`,
        });
      }
    }
  }
  return manifest;
}

export function loadContract(dir) {
  const errors = [];
  const surfaceParsed = readYaml(dir, SURFACE_FILE, errors);
  const personasParsed = readYaml(dir, PERSONAS_FILE, errors);
  const observablesParsed = readYaml(dir, OBSERVABLES_FILE, errors);
  const manifestParsed = readYaml(dir, MANIFEST_FILE, errors);

  const surface = validateSurface(surfaceParsed, errors);
  const personas = validatePersonas(personasParsed, errors);
  const observables = observablesParsed && typeof observablesParsed === "object" ? observablesParsed : {};
  const manifest = validateManifest(manifestParsed, errors);

  return { surface, personas, observables, manifest, errors };
}

// kebab-case or snake_case -> camelCase ("opportunity-cwu-view" -> "opportunityCwuView").
function toCamel(id) {
  const parts = String(id).split(/[-_]/).filter(Boolean);
  return parts.map((p, i) => (i === 0 ? p.toLowerCase() : capitalize(p))).join("");
}

// kebab-case or snake_case -> PascalCase, for a type name ("opportunity-cwu-view" ->
// "OpportunityCwuView").
function toPascal(id) {
  return String(id).split(/[-_]/).filter(Boolean).map(capitalize).join("");
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
}

// `surface.d.ts`: a `Surface` interface with the two fixed sign-in/out methods plus one
// property per page, and one `<Pascal>Page` interface per page with `open` plus one
// method per action (returns `Promise<void>`) and observation (returns `Promise<string>`).
// Pages, actions and observations are emitted in the order the YAML lists them — not
// sorted — so the generated file reads the way the contract does.
function generateSurfaceDts(contract) {
  const pages = contract.surface.pages;
  const lines = [HEADER, 'import type { Persona } from "./personas";', "", "export interface Surface {"];
  lines.push("  signIn(persona: Persona): Promise<void>;");
  lines.push("  signOut(): Promise<void>;");
  for (const page of pages) {
    lines.push(`  ${toCamel(page.id)}: ${toPascal(page.id)}Page;`);
  }
  lines.push("}");
  for (const page of pages) {
    lines.push("", `export interface ${toPascal(page.id)}Page {`);
    lines.push("  open(params?: Record<string, string>): Promise<void>;");
    for (const action of Object.keys(page.actions || {})) {
      lines.push(`  ${toCamel(action)}(input?: unknown): Promise<void>;`);
    }
    for (const observation of Object.keys(page.observations || {})) {
      lines.push(`  ${toCamel(observation)}(): Promise<string>;`);
    }
    lines.push("}");
  }
  return lines.join("\n") + "\n";
}

// `personas.ts`: one entry per persona, keyed by camelCase id, keeping only `id`, `can`
// (defaulting to `[]`) and `signIn` (the YAML's `sign_in`, or `null` when the persona
// names none) — `domain` and anything else on the source persona is dropped. The object
// is written with `JSON.stringify(..., null, 2)` rather than hand-built lines so the
// output is byte-stable for the same input without the generator having to reimplement
// JSON's own quoting and indentation rules.
function generatePersonasTs(contract) {
  const persona = {};
  for (const p of contract.personas.personas) {
    persona[toCamel(p.id)] = {
      id: p.id,
      can: Array.isArray(p.can) ? p.can : [],
      signIn: p.sign_in !== undefined ? p.sign_in : null,
    };
  }
  return (
    `${HEADER}\n` +
    `export const persona = ${JSON.stringify(persona, null, 2)} as const;\n\n` +
    `export type Persona = typeof persona[keyof typeof persona];\n`
  );
}

// `seed.ts`: the manifest verbatim except for its top-level `description`, which is prose
// for a person reading the YAML and not a handle any test refers to.
function generateSeedTs(contract) {
  const { description, ...seed } = contract.manifest || {};
  return (
    `${HEADER}\n` +
    `export const seed = ${JSON.stringify(seed, null, 2)} as const;\n\n` +
    `export type Seed = typeof seed;\n`
  );
}

export function generateTypes(contract) {
  return {
    "tests/generated/surface.d.ts": generateSurfaceDts(contract),
    "tests/generated/personas.ts": generatePersonasTs(contract),
    "tests/generated/seed.ts": generateSeedTs(contract),
  };
}

// Refuses to generate from a contract that failed to load cleanly (a page with no route
// would otherwise silently produce `undefined: undefinedPage;`), then writes only the
// files whose content actually changed, so a re-run over an already-generated project
// touches nothing and a check that diffs `tests/generated/*` sees real drift only.
export function writeGenerated(dir) {
  const contract = loadContract(dir);
  if (contract.errors.length > 0) {
    const summary = contract.errors.map((e) => `${e.file}: ${e.message}`).join("\n");
    throw new Error(`cannot generate tests: the contract has errors:\n${summary}`);
  }
  const files = generateTypes(contract);
  const written = [];
  for (const [relPath, text] of Object.entries(files)) {
    const abs = join(dir, relPath);
    let existing;
    try {
      existing = readText(abs);
    } catch (e) {
      if (e.code !== "ENOENT") throw e;
      existing = undefined;
    }
    if (existing !== text) {
      writeText(abs, text);
      written.push(relPath);
    }
  }
  return written;
}
